# Generated by Django 5.2 on 2025-04-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagementMono', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
